# Site settings
title: RITPagans
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Rochester Institute of Technology - Pagan "Club" / student life thing.
url: "http://ritpagans.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author:
      image:
